config/routes.rb
Rails.application.routes.draw do

  # verb '/path', to: "controller#action", as: :nickname

  get '/about', to: "pages#about", as: :about_us
  get '/contact', to: "pages#contact", as: :contact

  # get '/', to: "pages#home", as: :home
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

  def contact

  end

  def home
    @greeting = "Hello"
    @member = params[:member]
    @staff = ["Maria", "Alex", "Alex", "Pavel", "Renee"]
    if @member
      @staff = @staff.select { |staff_member| staff_member.starts_with?(@member)}
    end
    raise
    greet("Alex")
  end


  def greet(name)
    return "Hello there " name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Day 1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!-- <a href="/link">ANCHOR TEXT</a> -->
    <!-- link_to "ANCHOR TEXT", path -->
    <%= link_to "Contact", contact_path %>
    <%= link_to "About", about_us_path %>
    <%= link_to "Home", root_path %>
    <%= yield %>
    <footer>made with 💌 at le wagon</footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is my about page</h1>

app/views/pages/contact.html.erb
<h1>This is my contact page</h1>

app/views/pages/home.html.erb
<h1>This is my home page</h1>
<h2><%= @greeting %></h2>
<!-- get '/contact', to: "pages#contact", as: :contact -->
<!-- action = path -->
<!-- method = verb -->
<form action="/" method="get">
  <input type="text" name="member" placeholder="Who are you looking for?">
  <input type="submit">
</form>
<h4>You searched for <%= @member %></h4>
<ul>
  <% @staff.each do |staff|%>
    <li><%= staff %></li>
  <% end %>
</ul>